---
title: "First Knit"
author: "Madeleine Alseryani"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
    toc_depth: '5'
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 5
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  I went to Quartz Hill High School and graduated in 2019. If I were to compare math and english class, I would have to choose math. The class I did the best in was chemistry, which also involves a lot of math. Chemistry is the class I excell in the most. 

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  I have an apple laptop. Specifically, it is a Macbook air. On a scale 1-10, if I had to rate myself on how good I am with computer stuff, I would rate myself a 7. I also have internet access that it is decent.
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  I prefer to be called 'Madeleine' by my classmates and instructor.
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  As of right now, I want to graduate from a university and work a comfortable job. I want to be able to travel and learn different cultures. The college subject that interests me the most is psychobiology because, it is a mix of psychology and biology. I am striving to become a dentist. However, I have been torn between dentistry or law. 
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  I have gone to the countries of Mexico and Jordan. I do want to visit as many countries as I can in the future such as; Palestine, Turkey, Belgium, South Korea, and many more. I have never been in the military. If I got drafted, I would choose the air force since it is the branch that has the most amount of women enrolled.
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  I took Math 115 a year ago and received an A. I did not know that Math 115 only satisfies a general education requirement. I had to petition to take math 116 so that the institutions I applied to can accept it for transfer. My goal is to receive an A in the class. I plan on always making it to class and completing every assignment. I also plan on participating and asking for help when I need it or watching the recorded lecture on my time. 
   
 






  




